@extends('admin.layouts.app', ['title' => __('messages.admin.dashboard')])
@section('content')
<div class="page-header d-print-none mb-3"><h2 class="page-title">{{ __('messages.admin.dashboard') }}</h2><div class="text-secondary">{{ __('messages.admin.analytics_overview') }}</div></div>
<div class="row row-deck row-cards mb-4">
@foreach([
['label'=>'Total Visits','value'=>$stats['visits']],['label'=>'Unique Visitors','value'=>$stats['unique_visitors']],['label'=>'Project Views','value'=>$stats['project_views']],['label'=>'Demo Clicks','value'=>$stats['demo_clicks']],['label'=>'WhatsApp Clicks','value'=>$stats['whatsapp_clicks']],['label'=>'Telegram Clicks','value'=>$stats['telegram_clicks']],['label'=>'Contact Submissions','value'=>$stats['contact_submissions']],['label'=>'Feedback Reports','value'=>$stats['feedback_reports']],
] as $card)
<div class="col-sm-6 col-lg-3"><div class="card card-sm"><div class="card-body"><div class="font-weight-medium">{{ $card['value'] }}</div><div class="text-secondary">{{ app()->getLocale()==='ar' ? __($card['label']) : $card['label'] }}</div></div></div></div>
@endforeach
</div>
<div class="row row-cards">
<div class="col-lg-6"><div class="card"><div class="card-header"><h3 class="card-title">{{ __('messages.admin.top_pages') }}</h3></div><div class="table-responsive"><table class="table card-table"><thead><tr><th>{{ __('messages.admin.table.page') }}</th><th class="text-end">{{ __('messages.admin.table.views') }}</th></tr></thead><tbody>@forelse($topPages as $page)<tr><td>{{ $page->page_slug }}</td><td class="text-end">{{ $page->total }}</td></tr>@empty<tr><td colspan="2" class="text-center text-secondary py-3">{{ __('messages.admin.no_data') }}</td></tr>@endforelse</tbody></table></div></div></div>
<div class="col-lg-6"><div class="card"><div class="card-header"><h3 class="card-title">{{ __('messages.admin.top_projects') }}</h3></div><div class="table-responsive"><table class="table card-table"><thead><tr><th>{{ __('messages.admin.projects') }}</th><th class="text-end">{{ __('messages.admin.table.events') }}</th></tr></thead><tbody>@forelse($topProjects as $row)<tr><td>{{ $row->project?->title ?? 'Unknown' }}</td><td class="text-end">{{ $row->total }}</td></tr>@empty<tr><td colspan="2" class="text-center text-secondary py-3">{{ __('messages.admin.no_data') }}</td></tr>@endforelse</tbody></table></div></div></div>
<div class="col-12"><div class="card"><div class="card-header d-flex justify-content-between"><h3 class="card-title">{{ __('messages.admin.recent_submissions') }}</h3><a href="{{ route('admin.inbox.index') }}" class="btn btn-sm btn-primary">{{ __('messages.admin.open_inbox') }}</a></div><div class="table-responsive"><table class="table card-table"><thead><tr><th>{{ __('messages.admin.table.type') }}</th><th>{{ __('messages.admin.table.subject') }}</th><th>{{ __('messages.admin.table.date') }}</th></tr></thead><tbody>@forelse($recentSubmissions as $item)<tr><td>{{ $item['type'] }}</td><td>{{ $item['subject'] }}</td><td>{{ $item['created_at']->format('Y-m-d H:i') }}</td></tr>@empty<tr><td colspan="3" class="text-center text-secondary py-3">{{ __('messages.admin.no_submissions') }}</td></tr>@endforelse</tbody></table></div></div></div>
</div>
@endsection
