@extends('admin.layouts.app', ['title' => 'Inbox'])
@section('content')
<div class="page-header d-print-none mb-3"><h2 class="page-title">Inbox</h2><div class="text-secondary">Manage contacts, feedback, and demo requests.</div></div>
<div class="row row-cards mb-3"><div class="col-md-4"><a class="card card-link {{ $box==='contacts' ? 'border-primary' : '' }}" href="{{ route('admin.inbox.index',['box'=>'contacts']) }}"><div class="card-body"><strong>{{ $counts['contacts'] }}</strong> Contact Messages</div></a></div><div class="col-md-4"><a class="card card-link {{ $box==='feedback' ? 'border-primary' : '' }}" href="{{ route('admin.inbox.index',['box'=>'feedback']) }}"><div class="card-body"><strong>{{ $counts['feedback'] }}</strong> Feedback Reports</div></a></div><div class="col-md-4"><a class="card card-link {{ $box==='demo' ? 'border-primary' : '' }}" href="{{ route('admin.inbox.index',['box'=>'demo']) }}"><div class="card-body"><strong>{{ $counts['demo'] }}</strong> Demo Requests</div></a></div></div>
<div class="card"><div class="table-responsive"><table class="table card-table table-vcenter"><thead><tr><th>Date</th><th>Name</th><th>Subject</th><th>Status</th><th>Action</th></tr></thead><tbody>
@if($box==='contacts')@foreach($contacts as $item)<tr><td>{{ $item->created_at->format('Y-m-d H:i') }}</td><td>{{ $item->name }}</td><td>{{ $item->subject }}</td><td>{{ $item->status }}</td><td><form method="POST" action="{{ route('admin.inbox.contacts.update',$item) }}">@csrf @method('PATCH')<div class="d-flex gap-2"><select class="form-select form-select-sm" name="status">@foreach(['new','in_progress','resolved','ignored'] as $s)<option value="{{ $s }}" @selected($item->status===$s)>{{ $s }}</option>@endforeach</select><input class="form-control form-control-sm" name="admin_note" value="{{ $item->admin_note }}" placeholder="note"><button class="btn btn-sm btn-primary">Save</button></div></form></td></tr>@endforeach
@elseif($box==='feedback')@foreach($feedbacks as $item)<tr><td>{{ $item->created_at->format('Y-m-d H:i') }}</td><td>{{ $item->name }}<div class="small text-secondary">{{ $item->type }}</div></td><td>{{ $item->subject }}</td><td>{{ $item->status }}</td><td><form method="POST" action="{{ route('admin.inbox.feedback.update',$item) }}">@csrf @method('PATCH')<div class="d-flex gap-2"><select class="form-select form-select-sm" name="status">@foreach(['new','in_progress','resolved','ignored'] as $s)<option value="{{ $s }}" @selected($item->status===$s)>{{ $s }}</option>@endforeach</select><input class="form-control form-control-sm" name="admin_note" value="{{ $item->admin_note }}" placeholder="note"><button class="btn btn-sm btn-primary">Save</button></div></form></td></tr>@endforeach
@else @foreach($demoRequests as $item)<tr><td>{{ $item->created_at->format('Y-m-d H:i') }}</td><td>{{ $item->name }}<div class="small text-secondary">{{ $item->project?->title }}</div></td><td>{{ $item->message ?: '-' }}</td><td>{{ $item->status }}</td><td><form method="POST" action="{{ route('admin.inbox.demo.update',$item) }}">@csrf @method('PATCH')<div class="d-flex gap-2"><select class="form-select form-select-sm" name="status">@foreach(['new','in_progress','resolved','ignored'] as $s)<option value="{{ $s }}" @selected($item->status===$s)>{{ $s }}</option>@endforeach</select><input class="form-control form-control-sm" name="admin_note" value="{{ $item->admin_note }}" placeholder="note"><button class="btn btn-sm btn-primary">Save</button></div></form></td></tr>@endforeach @endif
</tbody></table></div></div>
@endsection
