@extends('admin.layouts.app', ['title' => __('messages.admin.inbox')])
@section('content')
<div class="page-header d-print-none mb-3"><h2 class="page-title">{{ __('messages.admin.inbox') }}</h2><div class="text-secondary">{{ __('messages.admin.inbox_help') }}</div></div>
<div class="row row-cards mb-3"><div class="col-md-4"><a class="card card-link {{ $box==='contacts' ? 'border-primary' : '' }}" href="{{ route('admin.inbox.index',['box'=>'contacts']) }}"><div class="card-body"><strong>{{ $counts['contacts'] }}</strong> {{ __('messages.admin.contact_messages') }}</div></a></div><div class="col-md-4"><a class="card card-link {{ $box==='feedback' ? 'border-primary' : '' }}" href="{{ route('admin.inbox.index',['box'=>'feedback']) }}"><div class="card-body"><strong>{{ $counts['feedback'] }}</strong> {{ __('messages.admin.feedback_reports') }}</div></a></div><div class="col-md-4"><a class="card card-link {{ $box==='demo' ? 'border-primary' : '' }}" href="{{ route('admin.inbox.index',['box'=>'demo']) }}"><div class="card-body"><strong>{{ $counts['demo'] }}</strong> {{ __('messages.admin.demo_requests') }}</div></a></div></div>
<div class="card"><div class="table-responsive"><table class="table card-table table-vcenter"><thead><tr><th>{{ __('messages.admin.table.date') }}</th><th>{{ __('messages.admin.table.name') }}</th><th>{{ __('messages.admin.table.subject') }}</th><th>{{ __('messages.admin.table.status') }}</th><th>{{ __('messages.admin.table.actions') }}</th></tr></thead><tbody>
@if($box==='contacts')@forelse($contacts as $item)<tr><td>{{ $item->created_at->format('Y-m-d H:i') }}</td><td>{{ $item->name }}</td><td>{{ $item->subject }}</td><td>{{ __('messages.admin.status.'.$item->status) }}</td><td><form method="POST" action="{{ route('admin.inbox.contacts.update',$item) }}">@csrf @method('PATCH')<div class="d-flex gap-2"><select class="form-select form-select-sm" name="status">@foreach(['new','in_progress','resolved','ignored'] as $s)<option value="{{ $s }}" @selected($item->status===$s)>{{ __('messages.admin.status.'.$s) }}</option>@endforeach</select><input class="form-control form-control-sm" name="admin_note" value="{{ $item->admin_note }}" placeholder="{{ __('messages.admin.admin_note') }}"><button class="btn btn-sm btn-primary">{{ __('messages.admin.save_status') }}</button></div></form></td></tr>@empty<tr><td colspan="5" class="text-center py-4 text-secondary">{{ __('messages.admin.no_data') }}</td></tr>@endforelse
@elseif($box==='feedback')@forelse($feedbacks as $item)<tr><td>{{ $item->created_at->format('Y-m-d H:i') }}</td><td>{{ $item->name }}<div class="small text-secondary">{{ $item->type }}</div></td><td>{{ $item->subject }}</td><td>{{ __('messages.admin.status.'.$item->status) }}</td><td><form method="POST" action="{{ route('admin.inbox.feedback.update',$item) }}">@csrf @method('PATCH')<div class="d-flex gap-2"><select class="form-select form-select-sm" name="status">@foreach(['new','in_progress','resolved','ignored'] as $s)<option value="{{ $s }}" @selected($item->status===$s)>{{ __('messages.admin.status.'.$s) }}</option>@endforeach</select><input class="form-control form-control-sm" name="admin_note" value="{{ $item->admin_note }}" placeholder="{{ __('messages.admin.admin_note') }}"><button class="btn btn-sm btn-primary">{{ __('messages.admin.save_status') }}</button></div></form></td></tr>@empty<tr><td colspan="5" class="text-center py-4 text-secondary">{{ __('messages.admin.no_data') }}</td></tr>@endforelse
@else @forelse($demoRequests as $item)<tr><td>{{ $item->created_at->format('Y-m-d H:i') }}</td><td>{{ $item->name }}<div class="small text-secondary">{{ $item->project?->title }}</div></td><td>{{ $item->message ?: '-' }}</td><td>{{ __('messages.admin.status.'.$item->status) }}</td><td><form method="POST" action="{{ route('admin.inbox.demo.update',$item) }}">@csrf @method('PATCH')<div class="d-flex gap-2"><select class="form-select form-select-sm" name="status">@foreach(['new','in_progress','resolved','ignored'] as $s)<option value="{{ $s }}" @selected($item->status===$s)>{{ __('messages.admin.status.'.$s) }}</option>@endforeach</select><input class="form-control form-control-sm" name="admin_note" value="{{ $item->admin_note }}" placeholder="{{ __('messages.admin.admin_note') }}"><button class="btn btn-sm btn-primary">{{ __('messages.admin.save_status') }}</button></div></form></td></tr>@empty<tr><td colspan="5" class="text-center py-4 text-secondary">{{ __('messages.admin.no_data') }}</td></tr>@endforelse @endif
</tbody></table></div></div>
@endsection
